# Generated by Django 2.2 on 2020-08-05 04:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('care_all', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='elder',
            name='age',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='youngster',
            name='age',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
