# Generated by Django 2.2 on 2020-08-05 04:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('care_all', '0002_auto_20200805_0933'),
    ]

    operations = [
        migrations.AlterField(
            model_name='elder',
            name='funds',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='youngster',
            name='elders_in_care',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
