# Generated by Django 2.2 on 2020-08-09 13:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('care_all', '0004_auto_20200805_1004'),
    ]

    operations = [
        migrations.AddField(
            model_name='elder',
            name='in_care',
            field=models.BooleanField(blank=True, default=False),
        ),
        migrations.AlterField(
            model_name='elder',
            name='status',
            field=models.CharField(choices=[('Available', 'Available'), ('Un-Available', 'Un-Available')], default='Available', max_length=20),
        ),
    ]
