# Generated by Django 2.2 on 2020-08-11 12:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('care_all', '0005_auto_20200809_1909'),
    ]

    operations = [
        migrations.CreateModel(
            name='CareRequest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('requester_for', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='care_all.Elder')),
                ('sender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='care_all.Youngster')),
            ],
        ),
    ]
