# Generated by Django 2.2 on 2020-08-12 01:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('care_all', '0006_carerequest'),
    ]

    operations = [
        migrations.RenameField(
            model_name='carerequest',
            old_name='requester_for',
            new_name='requested_for',
        ),
    ]
