# Generated by Django 2.2 on 2020-08-14 08:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('care_all', '0007_auto_20200812_0714'),
    ]

    operations = [
        migrations.AddField(
            model_name='elder',
            name='care_giver',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='care_all.Youngster'),
        ),
    ]
