# Generated by Django 2.2 on 2020-08-17 15:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('care_all', '0008_elder_care_giver'),
    ]

    operations = [
        migrations.AlterField(
            model_name='elder',
            name='care_giver',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='care_all.Youngster'),
        ),
    ]
