# Generated by Django 2.2 on 2020-08-20 03:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('care_all', '0009_auto_20200817_2115'),
    ]

    operations = [
        migrations.CreateModel(
            name='Reviews',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('review_subject', models.CharField(max_length=50)),
                ('review_message', models.CharField(blank=True, max_length=255)),
                ('review_rating', models.IntegerField(default=1)),
                ('review_status', models.CharField(choices=[('New', 'New'), ('True', 'True'), ('False', 'False')], default='New', max_length=5)),
                ('review_created_date', models.DateTimeField(auto_now_add=True)),
                ('review_writer_elder', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='care_all.Elder')),
                ('review_writer_youngster', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='care_all.Youngster')),
                ('review_written_for_elder', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='for_elder', to='care_all.Elder')),
                ('review_written_for_youngster', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='for_youngster', to='care_all.Youngster')),
            ],
        ),
    ]
