# Generated by Django 2.2 on 2020-08-20 03:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('care_all', '0010_reviews'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reviews',
            name='review_writer_elder',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='care_all.Elder'),
        ),
        migrations.AlterField(
            model_name='reviews',
            name='review_writer_youngster',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='care_all.Youngster'),
        ),
        migrations.AlterField(
            model_name='reviews',
            name='review_written_for_elder',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='for_elder', to='care_all.Elder'),
        ),
        migrations.AlterField(
            model_name='reviews',
            name='review_written_for_youngster',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='for_youngster', to='care_all.Youngster'),
        ),
    ]
